# Generated by Django 4.1.7 on 2023-03-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_firstname_messages_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
