# Generated by Django 4.1.7 on 2023-03-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_messages_header_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='header_img',
        ),
    ]
