# Generated by Django 4.1.7 on 2023-03-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_image_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='userId',
            field=models.IntegerField(null=True),
        ),
    ]
