# Generated by Django 4.1.7 on 2023-03-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_image_camping_image_alter_image_canoeing_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_camping',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/camping/'),
        ),
        migrations.AlterField(
            model_name='image_canoeing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/canoeing/'),
        ),
        migrations.AlterField(
            model_name='image_hiking',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/hiking/'),
        ),
        migrations.AlterField(
            model_name='image_skydiving',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/skydiving/'),
        ),
    ]
