# Generated by Django 4.1.7 on 2023-03-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_image_campingg_image_canoeingg_image_hikingg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_camping',
            name='descrip',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='image_camping',
            name='labels',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='image_canoeing',
            name='descrip',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='image_canoeing',
            name='labels',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='image_hiking',
            name='descrip',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='image_hiking',
            name='labels',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='image_skydiving',
            name='descrip',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='image_skydiving',
            name='labels',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
