# Generated by Django 4.1.7 on 2023-03-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_image_camping_descrip_image_camping_labels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='headImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
