# Generated by Django 4.1.7 on 2023-03-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_messages_headimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='nOfmssages',
            field=models.IntegerField(null=True),
        ),
    ]
