# Generated by Django 4.1.7 on 2023-03-19 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_messages_nofmssages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='nOfmssages',
        ),
    ]
