# Generated by Django 4.1.7 on 2023-03-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_password_member_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nofms',
            field=models.IntegerField(null=True),
        ),
    ]
