# Generated by Django 4.1.7 on 2023-03-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_nofms'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='userId',
            field=models.IntegerField(null=True),
        ),
    ]
