# Generated by Django 4.1.7 on 2023-03-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_productsmodel_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductsModel',
        ),
    ]
