# Generated by Django 4.1.7 on 2023-03-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_delete_productsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/buygear')),
                ('manudate', models.DateField(max_length=200)),
                ('modeltype', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
    ]
